// actions Filmes

export const GET_FILMES = 'GET_FILMES';
export const ADICIONAR_FILME = 'ADICIONAR_FILME';
export const EXCLUIR_FILME = 'EXCLUIR_FILME';
export const EDITAR_DADOS_FILME = 'EDITAR_DADOS_FILME';

export const BUSCAR_FILMES = 'BUSCAR_FILMES';
export const BUSCAR_FILMES_DIRETOR = 'BUSCAR_FILMES_DIRETOR';

export const EXIBIR_FLASH = 'EXIBIR_FLASH';
export const NAO_EXIBIR_FLASH = 'NAO_EXIBIR_FLASH';
export const SET_ERRO_FORMULARIO = 'SET_ERRO_FORMULARIO';
